apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
      containers:
      - name: strapi
        image: ghcr.io/uniia-com-ua/strapi-api:latest
        ports:
        - containerPort: 1337
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "300m"
            memory: "768Mi"
        env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: APP_VERSION
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: NODE_ENV
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: PORT
        envFrom:
        - secretRef:
            name: strapi-secrets
        readinessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /_health
            port: 1337
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: uploads
          mountPath: /opt/app/public/uploads
        - name: tmp
          mountPath: /opt/app/.tmp
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: strapi-uploads
      - name: tmp
        persistentVolumeClaim:
          claimName: strapi-tmp