apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-uploads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-tmp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


